version: '3'
services:
  app:
    image: pet-events-app
    build:
      context: .
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@n72bzhzwyzgte7oh_high?TNS_ADMIN=/Wallet_OZARZE8P1JOTCP4N
      - SPRING_DATASOURCE_USERNAME=petseventus
      - SPRING_DATASOURCE_PASSWORD=Pets_eventbd.-6
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.driver.OracleDriver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_SHOW_SQL=true
      - TNS_ADMIN=/Wallet_OZARZE8P1JOTCP4N
    networks:
      - default
    volumes:
      - ./Wallet_OZARZE8P1JOTCP4N:/Wallet_OZARZE8P1JOTCP4N

networks:
  default:
    driver: bridge  